# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "appfigures"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Chong"]
  s.date = "2012-09-16"
  s.description = "AppFigures API ruby edition"
  s.email = "francis@ignition.hk"
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "lib/appfigures.rb",
    "lib/appfigures/data.rb",
    "lib/appfigures/external.rb",
    "lib/appfigures/rank.rb",
    "lib/appfigures/sale.rb",
    "lib/appfigures/user.rb",
    "test/appfigures_fixture.yml.default",
    "test/test_data.rb",
    "test/test_external.rb",
    "test/test_rank.rb",
    "test/test_sale.rb",
    "test/test_user.rb"
  ]
  s.homepage = "https://github.com/siuying/appfigures"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "AppFigures API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

